### ISSUE TITLE
Alexa devices not found

### ISSUE THREAD

**Issue by gkchim** [mabunixda/node-red-contrib-alexa-home#104]
Hi I am trying to set this up, but having little luck.

My nodered installation sits behind an NGINX reverse proxy. does that effect anything. 

on node red, it shows as the hub is online, but Alexa will not discover the new devicesi am creating on Node .

Home Assistant and Node Red are installed using docker

**Comment by mabunixda** [comment]
How is the nodered installation running? within a docker instance or as process?

**Comment by gkchim** [comment]
hI,

within docker as a container.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mabunixda** [comment]
You *must* run the container with ```--network host``` because docker cannot handle the ssdp/udp broadcast element. This is also valid for all the runtimes, so also for orchestrators likes kubernetes or nomad :( 

that is also the reason I ended up running my installation on a raspi and just proxy the access via traefik load balancer.

**Comment by gkchim** [comment]
thank you. I use portainer to manage my docker instances. do you know how I do this through portainer ?

can you point me to a link with instructions/a tutorial please.

thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mabunixda** [comment]
I assume you have to edit the [advanced settings](https://docs.portainer.io/v/ce-2.6/user/docker/containers/add#advanced-container-settings) of portainer. there should be an entry: [host](https://docs.portainer.io/v/ce-2.9/user/docker/networks) on the networks tab/view

**Comment by gkchim** [comment]
I have just moved it to the host network. and now the 'Amazon Echo Hub' in Node Red says underneath ' Unable to start on port 80'

**Comment by gkchim** [comment]
Port 80 is my Nginx reverse proxy

**Comment by gkchim** [comment]
in my Node Red Docker logs i see the below error:

,
> node-red-docker@2.0.6 start /usr/src/node-red,
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data",
,
1 Oct 09:45:12 - [info] ,
,
Welcome to Node-RED,
===================,
,
1 Oct 09:45:13 - [info] Node-RED version: v2.0.6,
1 Oct 09:45:13 - [info] Node.js  version: v14.17.6,
1 Oct 09:45:13 - [info] Linux 5.10.0-0.bpo.8-amd64 x64 LE,
1 Oct 09:45:13 - [info] Loading palette nodes,
1 Oct 09:45:18 - [info] Settings file  : /data/settings.js,
1 Oct 09:45:18 - [info] Context store  : 'default' [module=memory],
1 Oct 09:45:18 - [info] User directory : /data,
1 Oct 09:45:18 - [warn] Projects disabled : editorTheme.projects.enabled=false,
1 Oct 09:45:18 - [info] Flows file     : /data/flows.json,
1 Oct 09:45:18 - [warn] ,
,
---------------------------------------------------------------------,
Your flow credentials file is encrypted using a system-generated key.,
,
If the system-generated key is lost for any reason, your credentials,
file will not be recoverable, you will have to delete it and re-enter,
your credentials.,
,
You should set your own key using the 'credentialSecret' option in,
your settings file. Node-RED will then re-encrypt your credentials,
file using your chosen key the next time you deploy a change.,
---------------------------------------------------------------------,
,
1 Oct 09:45:18 - [info] Server now running at http://127.0.0.1:1880/,
1 Oct 09:45:18 - [info] Starting flows,
1 Oct 09:45:18 - [info] Started flows,
1 Oct 09:45:18 - [error] Error: listen EACCES: permission denied 0.0.0.0:80,
1 Oct 09:46:59 - [error] Error: listen EACCES: permission denied 0.0.0.0:80,

**Comment by mabunixda** [comment]
try to set an environment variable ALEXA_PORT or change the configuration of the controller node settings.

**Comment by gkchim** [comment]
Should i set this to ALEXA_PORT = 80?

**Comment by gkchim** [comment]
configuration of the controller node settings. to a different port? that's not 80?

**Comment by gkchim** [comment]
i changed the configuration of the controller node settings to another number, now it says Alexa Hub is online. i will try and discover divies on Alexa now

**Comment by gkchim** [comment]
No luck discovering yet. this is my flow. Anything i have done wrong you can see?L

`[
    {
        "id": "373e0bcd.625e24",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "245783cc.6e10fc",
        "type": "debug",
        "z": "373e0bcd.625e24",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1290,
        "y": 640,
        "wires": []
    },
    {
        "id": "d73212da891aa831",
        "type": "amazon-echo-device",
        "z": "373e0bcd.625e24",
        "name": "Chair",
        "topic": "",
        "x": 1130,
        "y": 640,
        "wires": [
            [
                "245783cc.6e10fc"
            ]
        ]
    },
    {
        "id": "60e5d97e9c244c0b",
        "type": "amazon-echo-hub",
        "z": "373e0bcd.625e24",
        "port": "9084",
        "processinput": 0,
        "discovery": true,
        "x": 310,
        "y": 520,
        "wires": [
            [
                "1c5b693a9a6b412a",
                "009cdf100288bbc9"
            ]
        ]
    },
    {
        "id": "1c5b693a9a6b412a",
        "type": "link out",
        "z": "373e0bcd.625e24",
        "name": "Alexa Out",
        "links": [
            "985d7c76540cf8ad"
        ],
        "x": 950,
        "y": 440,
        "wires": [],
        "l": true
    },
    {
        "id": "985d7c76540cf8ad",
        "type": "link in",
        "z": "373e0bcd.625e24",
        "name": "Alexa in",
        "links": [
            "1c5b693a9a6b412a"
        ],
        "x": 1210,
        "y": 420,
        "wires": [
            [
                "d73212da891aa831"
            ]
        ],
        "l": true
    },
    {
        "id": "009cdf100288bbc9",
        "type": "debug",
        "z": "373e0bcd.625e24",
        "name": "firststep",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 520,
        "y": 340,
        "wires": []
    }
]`

**Comment by gkchim** [comment]
`
[
    {
        "id": "373e0bcd.625e24",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "245783cc.6e10fc",
        "type": "debug",
        "z": "373e0bcd.625e24",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1290,
        "y": 640,
        "wires": []
    },
    {
        "id": "d73212da891aa831",
        "type": "amazon-echo-device",
        "z": "373e0bcd.625e24",
        "name": "Chair",
        "topic": "",
        "x": 1130,
        "y": 640,
        "wires": [
            [
                "245783cc.6e10fc"
            ]
        ]
    },
    {
        "id": "60e5d97e9c244c0b",
        "type": "amazon-echo-hub",
        "z": "373e0bcd.625e24",
        "port": "9084",
        "processinput": 0,
        "discovery": true,
        "x": 310,
        "y": 520,
        "wires": [
            [
                "1c5b693a9a6b412a",
                "009cdf100288bbc9"
            ]
        ]
    },
    {
        "id": "1c5b693a9a6b412a",
        "type": "link out",
        "z": "373e0bcd.625e24",
        "name": "Alexa Out",
        "links": [
            "985d7c76540cf8ad"
        ],
        "x": 950,
        "y": 440,
        "wires": [],
        "l": true
    },
    {
        "id": "985d7c76540cf8ad",
        "type": "link in",
        "z": "373e0bcd.625e24",
        "name": "Alexa in",
        "links": [
            "1c5b693a9a6b412a"
        ],
        "x": 1210,
        "y": 420,
        "wires": [
            [
                "d73212da891aa831"
            ]
        ],
        "l": true
    },
    {
        "id": "009cdf100288bbc9",
        "type": "debug",
        "z": "373e0bcd.625e24",
        "name": "firststep",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 520,
        "y": 340,
        "wires": []
    }
]
`

**Comment by gkchim** [comment]
[
    {
        "id": "373e0bcd.625e24",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "245783cc.6e10fc",
        "type": "debug",
        "z": "373e0bcd.625e24",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1290,
        "y": 640,
        "wires": []
    },
    {
        "id": "d73212da891aa831",
        "type": "amazon-echo-device",
        "z": "373e0bcd.625e24",
        "name": "Chair",
        "topic": "",
        "x": 1130,
        "y": 640,
        "wires": [
            [
                "245783cc.6e10fc"
            ]
        ]
    },
    {
        "id": "60e5d97e9c244c0b",
        "type": "amazon-echo-hub",
        "z": "373e0bcd.625e24",
        "port": "9084",
        "processinput": 0,
        "discovery": true,
        "x": 310,
        "y": 520,
        "wires": [
            [
                "1c5b693a9a6b412a",
                "009cdf100288bbc9"
            ]
        ]
    },
    {
        "id": "1c5b693a9a6b412a",
        "type": "link out",
        "z": "373e0bcd.625e24",
        "name": "Alexa Out",
        "links": [
            "985d7c76540cf8ad"
        ],
        "x": 950,
        "y": 440,
        "wires": [],
        "l": true
    },
    {
        "id": "985d7c76540cf8ad",
        "type": "link in",
        "z": "373e0bcd.625e24",
        "name": "Alexa in",
        "links": [
            "1c5b693a9a6b412a"
        ],
        "x": 1210,
        "y": 420,
        "wires": [
            [
                "d73212da891aa831"
            ]
        ],
        "l": true
    },
    {
        "id": "009cdf100288bbc9",
        "type": "debug",
        "z": "373e0bcd.625e24",
        "name": "firststep",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 520,
        "y": 340,
        "wires": []
    }
]

**Comment by gkchim** [comment]
,
> node-red-docker@2.0.6 start /usr/src/node-red,
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data",

1 Oct 10:02:26 - [info] ,
,
Welcome to Node-RED,
===================,
,
1 Oct 10:02:26 - [info] Node-RED version: v2.0.6,
1 Oct 10:02:26 - [info] Node.js  version: v14.17.6,
1 Oct 10:02:26 - [info] Linux 5.10.0-0.bpo.8-amd64 x64 LE,
1 Oct 10:02:27 - [info] Loading palette nodes,
1 Oct 10:02:31 - [info] Settings file  : /data/settings.js,
1 Oct 10:02:31 - [info] Context store  : 'default' [module=memory],
1 Oct 10:02:31 - [info] User directory : /data,
1 Oct 10:02:31 - [warn] Projects disabled : editorTheme.projects.enabled=false,
1 Oct 10:02:31 - [info] Flows file     : /data/flows.json,
1 Oct 10:02:31 - [info] Server now running at http://127.0.0.1:1880/,
1 Oct 10:02:31 - [warn] ,
,
---------------------------------------------------------------------,
Your flow credentials file is encrypted using a system-generated key.,
,
If the system-generated key is lost for any reason, your credentials,
file will not be recoverable, you will have to delete it and re-enter,
your credentials.,
,
You should set your own key using the 'credentialSecret' option in,
your settings file. Node-RED will then re-encrypt your credentials,
file using your chosen key the next time you deploy a change.,
---------------------------------------------------------------------,
,
1 Oct 10:02:31 - [info] Starting flows,
1 Oct 10:02:32 - [info] Started flows,
1 Oct 10:02:32 - [info] [server:Home Assistant] Connecting to http://192.168.1.42:8123,
1 Oct 10:02:32 - [info] [server:Home Assistant] Connected to http://192.168.1.42:8123

**Comment by mabunixda** [comment]
Can you use nginx to forward requests to the allocated port?

**Comment by mabunixda** [comment]
Hopefully the new implementation from #108  and #111  solve these problems
