### ISSUE TITLE
nodes stuck in "discovery (p: 60000)" mode

### ISSUE THREAD

**Issue by montagar3** [mabunixda/node-red-contrib-alexa-home#11]
(Using version 0.3.5) This issue just started yesterday. All the alexa-home nodes are showing "discovery (p:60000)". When I restart node-red, they all show "online (p:60000)" but after about 30 seconds they all change to "discovery (p: 60000)" and can't be accessed by my echo. Asking alexa to discover devices yields "no new devices found".

**Comment by montagar3** [comment]
Found the issue. I had copied the nodes from one flow to another and even though I deleted them from the previous node, there was some kind of conflict/confusion as alexa was listing multiple instances of the devices. I removed all of those devices, did a discovery and all seems to be back to normal.

**Comment by mabunixda** [comment]
Sorry - missed the notification from github ... 

Nice to fix this by yourself
