### ISSUE TITLE
TypeError: alexaHome.AlexaIPAddress is not a function

### ISSUE THREAD

**Issue by DENightOne** [mabunixda/node-red-contrib-alexa-home#119]
Installed yesterday on 3 different node red installs and get the following the moment I start up node red

TypeError: alexaHome.AlexaIPAddress is not a function
    at /root/.node-red/node_modules/node-red-contrib-alexa-home/alexa/alexa-hub.js:59:39
    at Layer.handle [as handle_request] (/root/.node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/.node-red/node_modules/express/lib/router/index.js:328:13)
    at /root/.node-red/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/root/.node-red/node_modules/express/lib/router/index.js:346:12)
    at next (/root/.node-red/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/root/.node-red/node_modules/express/lib/router/layer.js:91:12)

**To Reproduce**
Just load onto new node red install, configure a bulb or switch and deploy....throws error before you even search for new devices on alexa.  When I do run an alexa discover devices I oviously get no device found

**Expected behavior**
No error on startup.

**Screenshots**

**Desktop (please complete the following information):**
 - Alexa Devices generation [ 1x Echo Dot gen1, 3x Echo Dot gen3, 1x Echo Flex ]
 - node version [ e.g. 11.15.1 ] 16.16.0
 - npm version [ e.g. 6.7.0 ] 8.1.3
 - is docker used? [y/n] Tried 2 installed on normal node red / Debian and Alpine, tried once on Docker using docker compose

**Additional context**
First install was on existing node red, the other two installed where on Fresh node red installs.  It seams like the new AlexaIPAddress code released yesterday is causing the problem

**Comment by mabunixda** [comment]
@DENightOne are you running the controller node in proxy mode or in native port configuration?

**Comment by DENightOne** [comment]
In proxy mode: Attached screenshot


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by DENightOne** [comment]
I am testing so am running node red as follows:


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by DENightOne** [comment]
Sorry I had it the wrong way round.....I notice this in another open bug: "
alexa_hub_port can either be the node-red port, when running in proxy mode, otherwise the configured port from the controller node." meaning I have been running with the configured port on the controller node and not proxy mode.... however no matter how I run it I get the "TypeError: alexaHome.AlexaIPAddress is not a function" at startup.   When I curl port 80 or use the browser to go to port 80 I get the same error code.

![alexa-home](https://user-images.githubusercontent.com/24840753/193116516-4e73c755-541c-4ac0-a669-cbba39828502.png)
![Error](https://user-images.githubusercontent.com/24840753/193116520-54d4338b-ad75-4110-889f-a827970a802a.png)

**Comment by ka0n** [comment]
I can cofirm the error "TypeError: alexaHome.AlexaIPAddress is not a function" was introduced in v2.0.1 in my setup.

As a containment, I downgraded to v2.0.0 by changing my node-red addon settings in homeassistant to node-red-contrib-alexa-home@2.0.0

**Comment by mabunixda** [comment]
I published version [2.0.2](https://flows.nodered.org/node/node-red-contrib-alexa-home) which fixxes that error.

**Comment by DENightOne** [comment]
Thanks very much, downloaded 2.0.2 and can confirm it works as expected.  Light discovered and actionable.

**Comment by mabunixda** [comment]
Awesome :-)

**Comment by DENightOne** [comment]
Am testing so running node red with this:

ALEXA_PORT=80 node-red start

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
