### ISSUE TITLE
issues after adding a 26th device

### ISSUE THREAD

**Issue by tribbles3** [mabunixda/node-red-contrib-alexa-home#12]
I have 25 alexa nodes and everything is fine but when I add a 26th node I lose access to one of the previous nodes. The new (26th) node works but one previous node is no longer accessible. When I try to access that "lost" node, node-red display a debug message that it's trying to access an invalid device. Is there a hard limit to the number of devices?

**Comment by mabunixda** [comment]
There is a limit of nodes per provider node - each provider node serves 25 alexa command nodes. I must review the code if there is a problem in the current code when going of this split. I use more than 40 alexa nodes rights now

**Comment by tribbles3** [comment]
Is a provider node the same as a configuration node? Is there a way to how many provider nodes there are?

**Comment by mabunixda** [comment]
provider nodes are created dynamically when a limit of n / 25 is reached. but the id of the nodes get persisted on disk within DATA_DIR/alexa-home/. There must be a file with { "key": "$PORT", "value": "$ID" }. Port is per Default 60000 but can be changed with ALEXA_PORT environment variable.

**Comment by tribbles3** [comment]
There are 86 files in that folder, so does that mean that there are left over files from deleted nodes?

**Comment by mabunixda** [comment]
damn yeah missed the cleanup processing totally :-( 

I will get this done - so overdue to refactor some code fragments in this node

**Comment by mabunixda** [comment]
reimplementation is fixed and i  have about 36 nodes available now and its running nice :)

**Comment by tribbles3** [comment]
Did the update and I am unable to access any devices. I removed them all and tried to do discovery and none of them are being located.

**Comment by mabunixda** [comment]
Did you add the controller node also?
