### ISSUE TITLE
Question about visibility in Alexa Routines as a trigger.

### ISSUE THREAD

**Issue by macavelly** [mabunixda/node-red-contrib-alexa-home#126]
Hi,

This isn't a issues but I wanted to know if the simulated alexa device (the hue light) shows up as a trigger (under smart home) to be used in alexa routines.

I've been using node-red-contrib-amazon-echo but it doesn't show up as a trigger. Basically I'm looking to trigger an alexa routine when the device turns on/off.

Thanks for your work!

![al1](https://user-images.githubusercontent.com/17036758/211965823-9467508a-5e1a-4859-8669-9a7d230309ea.jpg)
![al2](https://user-images.githubusercontent.com/17036758/211965824-bf31feec-ad3c-4b29-addb-207738067aa7.jpg)

**Comment by mabunixda** [comment]
Yeah it should be detected as "normal" device...

Sorry for late answering...
