### ISSUE TITLE
on/off or dim command

### ISSUE THREAD

**Issue by SamNitro** [mabunixda/node-red-contrib-alexa-home#21]
in the old version you have a 

msg.on_off_command = true/false

how can i make that difference between on/off and dim command?

**Comment by mabunixda** [comment]
The logic happens [here](https://github.com/mabunixda/node-red-contrib-alexa-home/blob/c06a6ad85d6cbccb8d82cf246418316ed248dbc5/alexa/alexa-home.js#L59)

msg.payload.on=true || false will switch on or off
msg.payload.bri=[0...255] will dim.

**Comment by till69** [comment]
Yes, the "msg.on_off_command = true/false" was very useful ... please bring it back

**Comment by mabunixda** [comment]
@till69  do you need this as output?

**Comment by till69** [comment]
Any solution is ok, but we should be able to difference between on/off and number command.

**Comment by till69** [comment]
Another small problem: "Alexa, light to 50" results in bri 127 and bri_normalized 49.80392156862745

So, if you could round to integer would be great :)
