### ISSUE TITLE
off vs zero

### ISSUE THREAD

**Issue by till69** [mabunixda/node-red-contrib-alexa-home#23]
First, thanks for quick 1.0.4 release 👍 

"Alexa, turn light off" and "Alexa, turn light to 0" both result in command = "switch"

Zero should result in   command = "dim"   , even if result is the same for lights.
But for control of other devices (like TV) this would be very helpful ;)

Most helpful for me (and maybe others) would be an entry:
msg.payload.data = [on | off | 0...100]

**Comment by mabunixda** [comment]
Yeah i understand you with the dim command, but the input of "Alexa, turn light to 0" is 
```
{"on":false}
```
There is no brightness input available to detect a dim command :-(

**Comment by till69** [comment]
Ok ... too bad ... stupid Alexa :(

Thanks anyway!

**Comment by mabunixda** [comment]
yeah it would also be helpful that you get more information about which alexa device the request was spoken to :-(
