### ISSUE TITLE
change_direction always 0

### ISSUE THREAD

**Issue by Lyve1981** [mabunixda/node-red-contrib-alexa-home#25]
After updating from a very old version (<1) I was able to adjust everything so it works again. 

But no matter what kind of command I initiate, the property change_direction is always zero. In an older version, this value was -1 or +1 if I used the commands (example) "blind up" or "blind down".

As the member is still part of the msg, I'd assume that it should still work this way.

**Comment by Lyve1981** [comment]
Sry, forgot to mention my version: 1.0.4

**Comment by Lyve1981** [comment]
@mabunixda as the name suggests, you might be german. The original command I use is "Markise rauf/runter" and "Rollo rauf/runter", I freely translated it to english here :)

**Comment by tt2g89** [comment]
Hi @Lyve1981,
this Alexa-skill is emulating hue-devices, so how did you try to make Alexa know, what you want to tell her with "rauf" or "runter"? Those aren't used with lights. But if you have a cool solution or idea, that would be interesting. :)

**Comment by mabunixda** [comment]
@Lyve1981 sorry forgot to update hte issue ... the change_direction is in the next release - or in the dev branch already

**Comment by mabunixda** [comment]
@Lyve1981 version 1.1.0 contains the fix
