### ISSUE TITLE
As a user I want to have the ability to promote smart sockets (i.e. Osram Plug) to alexa

### ISSUE THREAD

**Issue by tt2g89** [mabunixda/node-red-contrib-alexa-home#29]
Hi @mabunixda,
awesome work and support from your side!
To make a distinction between at least lamps and smart sockets and to be able to better address the sockets, the distinction between lamps and sockets would be helpful. Hue supports this function by default.
Thanks in advance for checking the possibility.

BR tt2g

**Comment by mabunixda** [comment]
@tt2g89 i understand the problem but i do not know if alexa devices support those stuff :-( I already tried to make some progress to report temperature sensors to alexa without success

**Comment by tt2g89** [comment]
@mabunixda in the meanwhile I found another solution for this issue, thanks. I'll close the issue.
