### ISSUE TITLE
% value ?

### ISSUE THREAD

**Issue by bytec77** [mabunixda/node-red-contrib-alexa-home#3]
Is it possible to set an % value for example an window shutter. 

Now I get only "on" or "off"

**Comment by mabunixda** [comment]
can you sketch your flow? and what alexa command are you using?

You could use the "dim" command e.g. "alexa, dim <node-name> to 5" will output msg.bri = 5 
or you can use "alexa, dim <node-name> to 5 percent" will produce msg.bri = 0.05

**Comment by mabunixda** [comment]
going go close this ...
