### ISSUE TITLE
no device discover under some circumstances

### ISSUE THREAD

**Issue by gp195** [mabunixda/node-red-contrib-alexa-home#32]
Hi!
First of all thank you for your work.
V1.04 works well with standard Node-Red settings.js.
If I change settings.js to https and user and admin auth, no devices are detected by alexa. This worked well in old versions, before Alexa Controller was introduced.
Also, without this, but activated this line: httpAdminRoot: '/admin', there is the same problem with unvisible devices.

**Comment by mabunixda** [comment]
Can you try the dev branch?
This version will support your setup.

At the moment this current version on the branch has the limitation that some web component gets not correct restarted ....

**Comment by gp195** [comment]
Thank you, but unfortunately no change...

**Comment by mabunixda** [comment]
@gp195 no change? Do you have any logs available?

**Comment by gp195** [comment]
Hi,
I did a Node-Red minimal installation under W10 and was able to observe exactly the same behavior. Node-Red makes the following issues with enabled debug and Alexa search, if everything works:

6 Aug 10:16:22 - [info] Starting flows
6 Aug 10:16:22 - [debug] red/nodes/flows.start : starting flow : global
6 Aug 10:16:22 - [debug] red/nodes/flows.start : not starting disabled flow : 8bb9981c.1c95a
6 Aug 10:16:22 - [debug] red/nodes/flows.start : starting flow : 2c752d76.40540a
6 Aug 10:16:22 - [info] [alexa-home-controller:Alexa Controller] Alexa Controller - alexa-home - Starting SSDP
6 Aug 10:16:22 - [debug] Alexa Controller - announcing: http://*:1880/alexa-home/setup.xml
6 Aug 10:16:22 - [info] Assigning alexa-home nodes to this controller
6 Aug 10:16:22 - [info] Started flows
6 Aug 10:16:40 - [debug] Setup was requested
6 Aug 10:16:40 - [debug] Alexa Controller - Handling setup request
6 Aug 10:16:40 - [debug] Alexa Controller - sending baseUrl http://10.0.0.4:1880
6 Aug 10:16:40 - [debug] Setup was requested
6 Aug 10:16:40 - [debug] Alexa Controller - Handling setup request
6 Aug 10:16:40 - [debug] Alexa Controller - sending baseUrl http://10.0.0.4:1880
6 Aug 10:16:40 - [debug] Setup was requested
6 Aug 10:16:40 - [debug] Alexa Controller - Handling setup request
6 Aug 10:16:40 - [debug] Alexa Controller - sending baseUrl http://10.0.0.4:1880
6 Aug 10:16:40 - [debug] Setup was requested
6 Aug 10:16:40 - [debug] Alexa Controller - Handling setup request
6 Aug 10:16:40 - [debug] Alexa Controller - sending baseUrl http://10.0.0.4:1880
6 Aug 10:16:40 - [debug] Got lights api call
6 Aug 10:16:40 - [debug] Alexa Controller - handling api item list request: lights
6 Aug 10:16:40 - [debug] Alexa Controller - Sending zfkrD4Dasoam36KYVGLOdZGI9PHosGzzUe2zkQe0 #1 lights json to 10.0.0.5
6 Aug 10:16:40 - [debug] Got lights api call
6 Aug 10:16:40 - [debug] Alexa Controller - handling api item list request: lights
6 Aug 10:16:40 - [debug] Alexa Controller - Sending zfkrD4Dasoam36KYVGLOdZGI9PHosGzzUe2zkQe0 #1 lights json to 10.0.0.5
6 Aug 10:16:40 - [debug] Got lights api call
6 Aug 10:16:40 - [debug] Alexa Controller - handling api item list request: lights
6 Aug 10:16:40 - [debug] Alexa Controller - Sending zfkrD4Dasoam36KYVGLOdZGI9PHosGzzUe2zkQe0 #1 lights json to 10.0.0.5
6 Aug 10:16:40 - [debug] Got lights api call
6 Aug 10:16:40 - [debug] Alexa Controller - handling api item list request: lights
6 Aug 10:16:40 - [debug] Alexa Controller - Sending zfkrD4Dasoam36KYVGLOdZGI9PHosGzzUe2zkQe0 #1 lights json to 10.0.0.5

If "httpAdminRoot: '/ admin'" is turned on in settings.js, debug output is:

6 Aug 10:31:35 - [info] Starting flows
6 Aug 10:31:35 - [debug] red/nodes/flows.start : starting flow : global
6 Aug 10:31:35 - [debug] red/nodes/flows.start : not starting disabled flow : 8bb9981c.1c95a
6 Aug 10:31:35 - [debug] red/nodes/flows.start : starting flow : 2c752d76.40540a
6 Aug 10:31:35 - [info] [alexa-home-controller:Alexa Controller] Alexa Controller - alexa-home - Starting SSDP
6 Aug 10:31:35 - [debug] Alexa Controller - announcing: http://*:1880/alexa-home/setup.xml
6 Aug 10:31:35 - [info] Assigning alexa-home nodes to this controller
6 Aug 10:31:35 - [info] Started flows

No further activities during Alexa search!!!

**Comment by mabunixda** [comment]
Ok the httpRoot and httpAdminRoot paths setting will disrupt the detection because alexa devices do not respect subdirectories in their requests. they always send their requests to the root of the webserver. 
Because nodered is not available in the root, this setup will fail. 

This will be fixed in the next release and is already available in the dev branch

**Comment by gp195** [comment]
Not sure where to get actual branch, files in dev are much more older then  
in master?


Am .08.2019, 11:34 Uhr, schrieb Martin Buchleitner  
<notifications@github.com>:
