### ISSUE TITLE
Ability to update alexa after an change has occured to a light

### ISSUE THREAD

**Issue by madbear2000** [mabunixda/node-red-contrib-alexa-home#33]
Is there any way to let Alexa see the current values for the lights?
It would be really nice to see that after a different device changes the brightness or state

**Comment by mabunixda** [comment]
@madbear2000 you should be able to see the current value in the alexa app right now

**Comment by madbear2000** [comment]
How do I do that?
Do I need to route the result of a status? 
Do I need to modify the JSON to match an output? The docs are not that clear about that part, and there is no good examples?

I had tried most of this and the best I could get was just Aleax reporting on or off but not the color or brightness.

**Comment by mabunixda** [comment]
Is [this](https://github.com/mabunixda/node-red-contrib-alexa-home/issues/28#issuecomment-508653120) helpful?

**Comment by madbear2000** [comment]
Hi mabunixda,
Thats is the page that I followed before raising this ticket. Its useful but not enough.
It does not state it the data format in the message. Ie should it be in msg.payload or msg,payload.data.
Should each element be a JSON object or a field.
For the brightness is that in percentage or integer values. 
For the colour is it the xy field? 
Just linking to your code is not great documentation

**Comment by mabunixda** [comment]
yeah correct- that was just a quickfix ... 
i gonna create a wiki page about this topic asap!

**Comment by mabunixda** [comment]
Hopefully the new implementation from #108  and #111  solve these problems
