### ISSUE TITLE
Multiple alexa support

### ISSUE THREAD

**Issue by MattL0** [mabunixda/node-red-contrib-alexa-home#4]
Can this plugin knows which echo dot ( i have 6 ) I am talking to? Thank you

**Comment by mabunixda** [comment]
With version 0.3.4 you can get the ip address of the device which is sending the request. At the moment there is not more information available within the communication with an alexa device.

**Comment by summer69guy** [comment]
Your talking about the Alexa device ? I am not sure where to look for the ip

**Comment by mabunixda** [comment]
the msg object has an additional property "alexa_ip". You can use this within a function block or a switch block do add additional logic. Just add an debug block and output the complete msg object

**Comment by summer69guy** [comment]
I didn’t output the complete message!! This is so nice. Thank youu !!

**Comment by summer69guy** [comment]
Hi,

I always get the same ip 192.168.1.1.

I tried with my phone, and with all my 6 Alexa dot v2

**Comment by mabunixda** [comment]
Is that an alexa dot ip ? Are you running node-red behind a reverse proxy?

**Comment by summer69guy** [comment]
Yes. this is a dot ip . I edited.

Today it shows 192.168.1.100. wich is also an echo dot ip. 

I tried all my echo dots. The Ip remain the same.

I do not really know what is a reverse proxy. But I use the last LEDE firmware on a Linksys WRT1900ACS

**Comment by summer69guy** [comment]
![capture](https://user-images.githubusercontent.com/27497561/37194101-a5671384-233a-11e8-8487-33c89d799368.PNG)

**Comment by summer69guy** [comment]
it is now 192.168.1.102.  wich is a dot too

**Comment by mabunixda** [comment]
i am not able to reproduce this because i just own one alexa device :-(

**Comment by summer69guy** [comment]
ok thank you . I'll wait then :P

**Comment by tb-killa** [comment]
Could somebody provide simple Example to Filter for the "alexa_ip" please ?

**Comment by summer69guy** [comment]
I always get the same ip. I think the plugin connect to a particular alexa at the begining when node red  loads ...and after that it is impossible to change that ip adress.  So the plugin detect one of my alexa at the begining... but after that it just tell me that everything is comming from that ip adress.. event if i call the device with another alexa.

If i restart nodered or my pc... the plugin will do the same behavior but with another alexa.. or the same one ..it depends..

----

but i was able to filter what i want from nodew red with this how to https://nodered.org/docs/getting-started/first-flow

**Comment by mabunixda** [comment]
The communication is the other way - alexa connects to node-red because this node adds an extra service which is discovered by alexa and afterwards alexa sends its commands to this service. But i assume that alexa does select a "master" node within its own network of alexas and only this alexa connects to the specific devices.

**Comment by MosesHill** [comment]
I was just about to write about this too. I have 3 Alexa and want to be able to say "Turn of the light", which should then turn of the primary light in the room where i am standing. Depending on, which Alexa I tell to do it, it will then be a different light.
But I have the same problem: the Alexa Home node only gets the IP of one of the Alexa devices ONCE. For the rest of the session this will be the only IP shown.

**Comment by summer69guy** [comment]
I have to say. If this feature works in the future. That would be a life changer for many !!!
Hope it is nota limitation on amazon side .

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by mabunixda** [comment]
Yeah i hope to get this done ... i just got a new echo dot these days and hope to get into testing asap!

**Comment by MosquitoD4K** [comment]
I have the same problem, as I receive the same IP address for every alexa I have. Would it be possible, to just add all information about the received request to the msg output? (all headers and all data)

**Comment by mabunixda** [comment]
Yeah it seems that only 1 alexa interacts with the node. I was also not able to get any information from available objects. 
I published a version 0.3.5 which adds all header information from the connection to the msg object. If you output the complete msg, they should appear in the log.

But i think i have to change the declaration of the hue gateway because other hue implementations ( switches and temperatures sensors ) are not checked by alexa right now :-(

**Comment by MosesHill** [comment]
Try look at the skill “This Room”. It is quite primitive, but on their webpage you can write an info for each room with an Alexa in it. The you get different information depending on, which Alexa you talk to (all in same Amazon account)

Marcel

**Comment by MosesHill** [comment]
Could be. I’m from denmark, so I just selected US.
But you can try to contact the website behind: http://actualcalories.com
Maybe they can tell you How to do it.

Hilsen Marcel

**Comment by jaburges** [comment]
Did you get anywhere with this? 
I too am getting the same IP address no matter what device (major bummer as really want to move to localized control based on the alexa device).
Is there any way to pull ANY unique ID for the device (MAC, UUID ?) 
Alexa App knows which device as can offer responses from the app to specific devices

**Comment by mabunixda** [comment]
Hi,

no i did no further work on this topic. But it is still something i am missing to. 
I will have to refactor the whole code to get also sensors available - i hope to get a solution also for this topic in this step

**Comment by mabunixda** [comment]
At the moment this is not solveable because how alexa devices act and just a single master is doing all communication. I saw that alexa app on mobile is going directly to devices, but that seems the only exception...
