### ISSUE TITLE
Controller node missing

### ISSUE THREAD

**Issue by biddster** [mabunixda/node-red-contrib-alexa-home#42]
I'm using node-red 1.0.0 beta3 with version 1.1.0 of this node and the controller node is missing from the palette. If I roll back to 1.0.4, the controller node re-appears and everything works correctly.

**Comment by nepeee** [comment]
Try to install the express module & restart node-red.
npm install express

**Comment by mabunixda** [comment]
i missed to insert express before 1.1.1 in the package.json as dependency. Please retry with this version.

**Comment by mabunixda** [comment]
@biddster please retry with version 1.1.2 - there this issue is definitly fixxed
