### ISSUE TITLE
Android Alexa app incorrectly shows off state after the light is turned on

### ISSUE THREAD

**Issue by nepeee** [mabunixda/node-red-contrib-alexa-home#45]
If you turn off the light in the app everything is ok, the app shows that it is turned off. But after that if you set it on the app shows that it is off.

The problem is caused by that the code is setting the brightness to 255 but the allowed maximum is 254 as in documented in the hue api specification:

> bri The brightness value to set the light  to.Brightness is a scale from 1 (the minimum the light is capable of) to  254 (the maximum).

Solution:
Simply replace the 255 in all javascript files to 254.

Also please don't change the brightness value when only an on/off command is received. (Change line 116 in alexa-home.js to):
`msg.payload.bri = node.bri;`
and line 24 to:
`node.bri = 254;`

This also fixes the "Device doesn't support requested value" warning in the app.

**Comment by mabunixda** [comment]
fixxed with commit #47 and will release it with fix of #46
