### ISSUE TITLE
Allow to bind to specific IP

### ISSUE THREAD

**Issue by Sk4zz** [mabunixda/node-red-contrib-alexa-home#57]
I'm using alexa-home on a Raspberry Pi which is also running deconz and piHole. I have configured two virtual network adapters on the pi so that the Pi is reachable at 192.168.2.10,11 and 12. Each of the services (deconz, pihole, nodered) is listening on a separate IP adress because (so far) both, deconz and pihole need to be reachable at port 80. 

I used to have alexa-home listening on port 60000 which was working fine until, umm..., some 10 days ago or so.

Unfortunately I am not very familiar with iptables and I couldn't find a example how to forward a port on a specific IP adress.

Is there a way to tell alexa-home to listen to port 80 on a specific IP adress? Or would it be possible to implement this feature in the configuration node?

Thank you for your great work!

**Comment by mabunixda** [comment]
Yeah i gonna redo this feature again

**Comment by mabunixda** [comment]
you must set ALEXA_IP to restrict binding to dedicated IP instead to all devices
