### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by apedance** [mabunixda/node-red-contrib-alexa-home#59]
Hey,

I am unable to install your node because there is "node-red-contrib-alexa-home-skill" already installed in node red which can not be uninstalled.

**Comment by mabunixda** [comment]
yes .. 2 alexa nodes cannot be used at the same time

**Comment by apedance** [comment]
> yes .. 2 alexa nodes cannot be used at the same time

and how can I get rid of the old one?
