### ISSUE TITLE
Unable to install node due to conflict.

### ISSUE THREAD

**Issue by ldh830114** [mabunixda/node-red-contrib-alexa-home#64]
I am unable to install the node as it states there is a conflict with node-red-contrib-alexa-home-skill.

I am unable to remove node-red-contrib-alexa-home-skill in palette manager. Has anyone else had the same issue? I am using Node-Red hass.io addon.

Thanks for the hard work.

**Comment by mabunixda** [comment]
sorry - no problems on this one. 

Are there any logs available?

**Comment by mabunixda** [comment]
no more input  - please feel free to reopen the issue
