### ISSUE TITLE
Bootloop if alexa-home node ist deployed without controller node.

### ISSUE THREAD

**Issue by ichbaum** [mabunixda/node-red-contrib-alexa-home#65]
2 Nov 19:49:14 - [info] Flows starten
2 Nov 19:49:17 - [info] [alexa-home-controller:Alexa Controller] 0 - alexa-home - Starting SSDP
2 Nov 19:49:17 - [info] [alexa-home-controller:Alexa Controller] 0 - announcing: http://*:80/alexa-home/setup.xml
2 Nov 19:49:17 - [info] Assigning alexa-home nodes to this controller
2 Nov 19:49:18 - [info] Flows gestartet
2 Nov 19:49:18 - [red] Uncaught Exception:
2 Nov 19:49:18 - Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1263:19)
    at listenInCluster (net.js:1328:12)
    at doListen (net.js:1461:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=100ms expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 5.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.

**Comment by mabunixda** [comment]
This boot loop is occuring because your running node-red user is not allowed to open port 80 as already discussed [here](https://github.com/mabunixda/node-red-contrib-alexa-home/issues/62#issuecomment-537203445)
