### ISSUE TITLE
unknown alexa node of type lights was requested: _emptyIteratorStopper

### ISSUE THREAD

**Issue by ichbaum** [mabunixda/node-red-contrib-alexa-home#66]
I can't add devices to alexa.
It worked onece. After i added more devices it won't work anymore. I get this error message.
I uninstalled/reinstalled it. Nothing worked.

The port 60000 is mapped via Iptables to 80.

```
3 Nov 15:25:10 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights
3 Nov 15:25:10 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /alexa-home/setup.xml
3 Nov 15:25:11 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/POST -> /api
3 Nov 15:25:11 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights
3 Nov 15:25:11 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/_emptyIteratorStopper
3 Nov 15:25:11 - [warn] unknown alexa node of type lights was requested: _emptyIteratorStopper
3 Nov 15:25:11 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/_emptyIteratorStopper
3 Nov 15:25:11 - [warn] unknown alexa node of type lights was requested: _emptyIteratorStopper

```

`{ "lights": { "37feaa82d77ad6": { "state": { "on": false, "bri": 254, "hue": 0, "sat": 254, "effect": "none", "xy": [ 0.0, 0.0 ], "ct": 199, "colormode": "ct", "reachable": true, "alert":"none", "mode":"homeautomation" }, "swupdate": { "state": "noupdates", "lastinstall": "2019-11-03T14:31:25" }, "type": "Dimmable light", "name": "Arbeitsfläche", "modelid": "LCT007", "manufacturername": "Philips", "productname": "Hue color lamp", "swversion": "5.105.0.21169", "uniqueid":"00:11:22:33:44:55:66:77-88" }, "_emptyIteratorStopper": {} }, "config":{"name":"Philips hue","mac":"00:00:00:aa:bb:cc","dhcp":true,"ipaddress":"192.168.1.116","netmask":"0.0.0.0","gateway":"0.0.0.0","proxyaddress":"","proxyport":0,"UTC":"2019-11-03T14:31:25","whitelist":{ "c6260f982b43a226b5542b967f612ce":{"last use date":"2019-11-03T14:31:25","create date":"2019-11-03T14:31:25","name":"Echo" }},"swversion":"01003372","swupdate":{ "updatestate":0, "url":"", "text":"", "notify":false},"linkbutton":false,"portalservices":false }}`

**Comment by mabunixda** [comment]
This is a known limitiation of the templating function used to generate the response data for alexa. If anybody can solve this with a valid json output i am happy to merge the pull request! 💯

**Comment by ichbaum** [comment]
This error prevents the whole system from working.
I adden 5 Lights. Everything was ok.
Than i added a new one and let alexa scan again. I got the error and ALL lights stop functioning.

`8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/291ee54a7597ba
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/291ee54a7597ba
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/291ee54a7597ba
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/291ee54a7597ba
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/1e67d169ebacff
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/1e67d169ebacff
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/1e67d169ebacff
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/1e67d169ebacff
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/da2aa3791cc48
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/da2aa3791cc48
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/da2aa3791cc48
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/da2aa3791cc48
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/61452be237a624
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/61452be237a624
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/61452be237a624
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/61452be237a624
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/a80a300124202
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/a80a300124202
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/a80a300124202
8 Nov 19:02:19 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/a80a300124202
8 Nov 19:02:21 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.129-60000/GET -> /alexa-home/setup.xml
8 Nov 19:02:22 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/a80a300124202
8 Nov 19:02:22 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/a80a300124202
8 Nov 19:02:22 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/a80a300124202
8 Nov 19:02:22 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/a80a300124202
8 Nov 19:02:24 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/PUT -> /api/c6260f982b43a226b5542b967f612ce/lights/a80a300124202/state
8 Nov 19:02:24 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/a80a300124202
TCP Timeout
8 Nov 19:02:26 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/PUT -> /api/c6260f982b43a226b5542b967f612ce/lights/a80a300124202/state
8 Nov 19:02:26 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/a80a300124202
TCP Timeout
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/291ee54a7597ba
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/291ee54a7597ba
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/291ee54a7597ba
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/291ee54a7597ba
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/1e67d169ebacff
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/1e67d169ebacff
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/1e67d169ebacff
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/1e67d169ebacff
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/da2aa3791cc48
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/da2aa3791cc48
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/da2aa3791cc48
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/da2aa3791cc48
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/61452be237a624
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/61452be237a624
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/61452be237a624
8 Nov 19:02:38 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/61452be237a624
8 Nov 19:02:40 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/1e67d169ebacff
8 Nov 19:02:40 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/1e67d169ebacff
8 Nov 19:02:40 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/1e67d169ebacff
8 Nov 19:02:40 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/1e67d169ebacff
8 Nov 19:02:41 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.129-60000/GET -> /alexa-home/setup.xml
TCP Timeout
8 Nov 19:02:50 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /alexa-home/setup.xml
8 Nov 19:02:50 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights
8 Nov 19:02:50 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/POST -> /api
8 Nov 19:02:50 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights
8 Nov 19:02:50 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/_emptyIteratorStopper
8 Nov 19:02:50 - [warn] unknown alexa node of type lights was requested: _emptyIteratorStopper
8 Nov 19:02:50 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.223-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/_emptyIteratorStopper
8 Nov 19:02:50 - [warn] unknown alexa node of type lights was requested: _emptyIteratorStopper
8 Nov 19:02:51 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.129-60000/GET -> /alexa-home/setup.xml
`
