### ISSUE TITLE
can't get api /state JSON

### ISSUE THREAD

**Issue by ichbaum** [mabunixda/node-red-contrib-alexa-home#67]
Alexa trys to get the /state of an lamp after switching it on.
But gets connection errors. You can see it in the app. after a few seconds the state in the app is correct again. May be an api call to update all lamps.

![2019-11-04 06_07_28-192 168 1 116_api_c6260f982b43a226b5542b967f612ce_lights_a80a300124202](https://user-images.githubusercontent.com/9842110/68100683-8bde6400-fec9-11e9-8ce8-d2312db68c0d.png)
![2019-11-04 06_07_46-Error](https://user-images.githubusercontent.com/9842110/68100684-8bde6400-fec9-11e9-8300-6abd114f5894.png)

```
4 Nov 06:07:42 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.100-60000/GET -> /api/c6260f982b43a226b5542b967f612ce/lights/a80a300124202/state
4 Nov 06:07:47 - [info] [alexa-home-controller:Alexa Controller] 192.168.1.129-60000/GET -> /alexa-home/setup.xml
```

**Comment by mabunixda** [comment]
@ichbaum can you get the http headers from the non function http request?

**Comment by ichbaum** [comment]
`
User-Agent: | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
-- | --
DNT: | 1
Accept: | */*
Accept-Encoding: | gzip, deflate
Accept-Language: | de,de-DE;q=0.9,en;q=0.8,en-US;q=0.7
Cookie: | io=U6EeAl2XGzvJ8Oj3AAAA

`

Body
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/c6260f982b43a226b5542b967f612ce/lights/1421c926688fa7/state</pre>
</body>
</html> 
```

**Comment by ichbaum** [comment]
`

X-Powered-By: | Express
-- | --
Content-Security-Policy: | default-src 'none'
X-Content-Type-Options: | nosniff
Content-Type: | text/html; charset=utf-8
Content-Length: | 202 bytes
Date: | Fri, 08 Nov 2019 18:13:15 GMT
Connection: | keep-alive

`

**Comment by ichbaum** [comment]
And i get an defective JSON for this light.
http://192.168.1.116/api/c6260f982b43a226b5542b967f612ce/lights/1421c926688fa7

Unexpected token (COMMA(,)) at position 15

{"state":{"on":,"bri":254,"hue":0,"sat":254,"effect":"none","xy":[0,0],"ct":199,"alert":"none","colormode":"ct","mode":"homeautomation","reachable":true},"swupdate":{"state":"noupdates","lastinstall":"2019-11-08T18:18:12"},"type":"Extendedcolorlight","name":"LED","modelid":"LTW011","swversion":"1.29.0_r21169"}

**Comment by mabunixda** [comment]
Thanks for the input! i gonna review that

**Comment by mabunixda** [comment]
Hopefully the new implementation from #108  and #111  solve these problems
