### ISSUE TITLE
Can't discover devices (running Node-RED on docker)

### ISSUE THREAD

**Issue by resper** [mabunixda/node-red-contrib-alexa-home#7]
Hello,

Alexa doesn't find any device. I Open TCP and UDP Port 60.
I also get no error or warning in the log files.
![screenshot-192 168 178 27-1880-2018 04 05-00-36-59](https://user-images.githubusercontent.com/6404294/38338341-7f3c3f24-3869-11e8-9f3a-d2aa4d53f841.png)

**Comment by bagg3rs** [comment]
I had to move to host network from bridge.

**Comment by gregbert42** [comment]
Having the same problem!

**Comment by mabunixda** [comment]
Yeah docker does not support the udp multicast :-( You must run this on hostNetwork. I was not able to find any workaround until now
