### ISSUE TITLE
Update CHANGELOG.md on each release?

### ISSUE THREAD

**Issue by jcwren** [mabunixda/node-red-contrib-alexa-home#73]
First, let me say this is a great module, and has been very useful. In particular, I use it to make a house-wide annoucement when the driveway gate has been opened or closed. I'm really happy to see active development on the module.

Would it be possible to update the CHANGELOG.md for each release? It was last updated about 11 months ago, at version 1.0.0. I usually go back through the commit list to see what changed, but sometimes it's a little hard to tell what the reason for the change was or what it might affect if I update to a new release.

Thanks!

**Comment by mabunixda** [comment]
Yeah i know i have to get this done ... hopefully with some github action stuff.

Pull requests are welcome!
