### ISSUE TITLE
Device Malfunction when changing Color

### ISSUE THREAD

**Issue by AzonInc** [mabunixda/node-red-contrib-alexa-home#74]
Whenever I try to change the Color, Alexa is responding with "Device unreachable".
The Alexa App itself responds with: "Device Malfunction".

I'm using an Echo Dot 2nd Gen and the latest release of node-red-contrib-alexa-home.

Does this happen to me only or to others too?

**Comment by AzonInc** [comment]
While looking at the code it seems that it's not implemented properly.
Color Mode is ct but ct, hue and sat are never changed.
The response values for them are always static.

**Comment by mabunixda** [comment]
Thanks - i did not use that function at all the last few months myself. i gonna review the code

**Comment by mabunixda** [comment]
Hopefully the new implementation from #108  and #111  solve these problems
