### ISSUE TITLE
alexa cant discover devices

### ISSUE THREAD

**Issue by caster1** [mabunixda/node-red-contrib-alexa-home#78]
i have port forwarded port 80 with 
`sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 60000` 
and my command line is also starting it as '1 Jul 17:52:12 - [info] Stopped flows
1 Jul 17:52:12 - [info] Starting flows
1 Jul 17:52:12 - [info] [alexa-home-controller:Alexa Controller] 0 - alexa-home - Starting SSDP
1 Jul 17:52:12 - [info] [alexa-home-controller:Alexa Controller] 0 - announcing: http://*:60000/alexa-home/setup.xml
1 Jul 17:52:12 - [info] Assigning alexa-home nodes to this controller
1 Jul 17:52:12 - [info] Started flows
1 Jul 17:52:13 - [info] [mqtt-broker:192.168.43.69] Connected to broker: mqtt://192.168.43.69:1883
'
but my alexa cant discover it im adding it via other in the devices option . please help me out

**Comment by mabunixda** [comment]
Hi, you can also define on the Alexa Controller Node that it should be listening to port 80! Go on configuration of the node and change the port ... and drop your iptables rules oc

**Comment by caster1** [comment]
hi thank  you mabuxinda when i start on port 80 its crashing there is something running on the address 0.0.0.0.80 i checked it but there is nothing running on that port this is my log
`2 Jul 07:16:40 - [info] Starting flows
2 Jul 07:16:41 - [info] [alexa-home-controller:Alexa Controller] 0 - alexa-home - Starting SSDP
2 Jul 07:16:41 - [info] [alexa-home-controller:Alexa Controller] 0 - announcing: http://*:80/alexa-home/setup.xml
2 Jul 07:16:41 - [info] Assigning alexa-home nodes to this controller
2 Jul 07:16:41 - [info] Started flows
2 Jul 07:16:41 - [red] Uncaught Exception:
2 Jul 07:16:41 - Error: listen EADDRINUSE: address already in use 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at doListen (net.js:1500:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
  

sudo lsof -i -P -n | grep LISTEN
mosquitto 342 mosquitto    5u  IPv4  12853      0t0  TCP *:1883 (LISTEN)
mosquitto 342 mosquitto    6u  IPv6  12854      0t0  TCP *:1883 (LISTEN)
vncserver 359      root   10u  IPv6  13269      0t0  TCP *:5900 (LISTEN)
vncserver 359      root   11u  IPv4  13270      0t0  TCP *:5900 (LISTEN)

`

**Comment by caster1** [comment]
okay now i created a new flow with node-red new_flow.json its begin and i started my controller on port 80 but still my alea can not discover it
`2 Jul 07:50:39 - [info] Starting flows
2 Jul 07:50:39 - [info] [alexa-home-controller:Alexa Controller] 0 - alexa-home - Starting SSDP
2 Jul 07:50:40 - [info] [alexa-home-controller:Alexa Controller] 0 - announcing: http://*:80/alexa-home/setup.xml
2 Jul 07:50:40 - [info] Assigning alexa-home nodes to this controller
2 Jul 07:50:40 - [info] Started flows
2 Jul 07:50:40 - [info] [mqtt-broker:192.168.43.69] Connected to broker: mqtt://192.168.43.69:1883
`

**Comment by mabunixda** [comment]
Is there an echo available within the network?

**Comment by caster1** [comment]
no there isnt i only have an alexa client on my phone, would this work if i buy an alexa?

**Comment by mabunixda** [comment]
Yeah i did not test with just the phone. As far as i know you can only interact with alexa devices

**Comment by jeffellington13** [comment]
To be successful on port 80, Node-Red needs to be running as root. If this instance of Node-Red is running on Raspian it will not natively work on port 80. There is documentation on the www on how to run Node-Red as root.

**Comment by mabunixda** [comment]
Hopefully the new implementation from #108  and #111  solve these problems
