### ISSUE TITLE
Dim light is set as a Ct dim light 

### ISSUE THREAD

**Issue by MattL0** [mabunixda/node-red-contrib-alexa-home#87]
I get this error on nodered when alexa is discovering devices.
I have set all the lights type in nodered  to : dimmable light. But they are set to ct light in the alexa app. Testing a ct level gives a ''device malfunction'' response on the app.

![Capture](https://user-images.githubusercontent.com/27497561/103964960-a8f46f80-512a-11eb-9e2f-f029fa7e68b8.PNG)

**Comment by mabunixda** [comment]
Hi Matt, the response _emptyIteratorStopper is just a formatting hack/fix to use a template engine to generate the response. 
i guess your problem is related to #77 - I am working on a new version right now to fix this problem

**Comment by MattL0** [comment]
Thanks Martin

**Comment by mabunixda** [comment]
Hopefully the new implementation from #108  and #111  solve these problems
