### ISSUE TITLE
Too many log entries

### ISSUE THREAD

**Issue by Werner-G** [mabunixda/node-red-contrib-alexa-home#9]
I moved from alexa-local to alexa-home with the hope not to have so many log entries - but it is still the same. My opinion is that log-files should be easy to read and to see some failures in one look. Is it possible to minimize log-entries to certain level?

**Comment by Toshibass** [comment]
Agreed the node is working fine for me but why is this node filling up my log file with unnecessary crap, all that's needed is an entry if something is wrong ... please fix this or O will have to delete this node as unusable.

**Comment by mabunixda** [comment]
Yeah i am refactoring the solution right now .. i gonna take this issue on

**Comment by mabunixda** [comment]
rewrite is going on in dev branch - hopefully this will workout with a new version by next week

**Comment by mabunixda** [comment]
logging is now refactored with #15 and release 1.0.0
